name: Sync Github Repos To Gitee

on:
  workflow_run:
    workflows: ["github pages"]
    branches:
      - main
    types:
      - completed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
      with:
        #Source warehouse
        source-repo: "git@github.com:braydenlee/braydenlee.github.io.git"
        #Target warehouse
        destination-repo: "git@gitee.com:braydenlee/braydenlee.git"
    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@main
      with:
        gitee-username: braydenlee
        gitee-password: ${{ secrets.GITEE_PASSWD }}
        gitee-repo: braydenlee/braydenlee
        branch: main
